# Generated by Django 5.0.3 on 2024-03-18 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('food_quantity', models.IntegerField()),
                ('type_of_food', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_donations_made', to='api.customuser')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_donations_received', to='api.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Donate_Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grocery_quantity', models.IntegerField()),
                ('type_of_grocery', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_donations_made', to='api.customuser')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_donations_received', to='api.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('help', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_helped', to='api.customuser')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to='api.customuser')),
            ],
        ),
    ]
