# Generated by Django 5.0.3 on 2024-03-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_donated_customuser_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='donated',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requested',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
